interface Source { label: string; href: string }
export interface AlternativeReview {
  topic: string;
  description: string;
  question: string;
  strengths: string[];
  checks: [string, string, string];
  sources: Source[];
  facts?: Partial<Record<"free" | "paid" | "domains" | "branding" | "routing" | "apps" | "analytics" | "fees", string>>;
  notice?: string;
  migrationOnly?: boolean;
}

// Reviewed against the linked primary sources on 2026-08-31. Unknown plan
// entitlements stay explicit instead of inheriting the legacy catalog's claims.
export const alternativeReviews: Record<string, AlternativeReview> = {
  linktree: {
    topic: "Profile pages & traffic rules",
    description: "Linktree combines a bio page with creator commerce and audience tools. Compare those workflows with Linktery’s managed links, country rules, and branded destinations.",
    question: "A creator toolkit, or more control over each destination?",
    strengths: ["Bio pages with themes, layouts, and media", "Selling tools and audience collection", "Advanced analytics on paid plans"],
    checks: ["Rebuild your highest-traffic page, including media and shop links, before switching your social bios.", "If you use Linktree selling tools, retain a separate checkout: Linktery does not process orders or deliver purchases.", "Compare your exact routing rules. Linktree lists smart routing on Premium; do not assume the two products support identical conditions."],
    facts: { free: "$0 plan", paid: "Starter, Pro, and Premium", domains: "Cannot replace the linktr.ee page URL", branding: "Removal on Pro and Premium", routing: "Premium lists smart routing; verify conditions", analytics: "Depth varies by plan", fees: "Selling fees vary by plan and product" },
    sources: [{ label: "Linktree plans", href: "https://linktr.ee/s/pricing" }, { label: "Custom-domain policy", href: "https://linktr.ee/help/en/articles/6571689-can-i-change-the-linktree-url-to-a-custom-domain" }],
  },
  beacons: {
    topic: "Creator commerce & campaign links",
    description: "Beacons brings a storefront, email tools, and a media kit into a creator workspace. Linktery is a different fit when sales happen elsewhere and you need to manage the traffic reaching them.",
    question: "Do you sell inside the bio tool or through an external store?",
    strengths: ["Integrated digital-product storefront", "Email marketing alongside the bio page", "Creator media kits and memberships"],
    checks: ["List the products, customer emails, and automations attached to your Beacons account before replacing its public link.", "Compare the total commerce cost, not only the subscription. Free and Creator have different fee terms from Creator Plus and Max.", "Test campaign tags through the full trip to your external store; a click report is not a payment confirmation."],
    facts: { free: "$0 plan", paid: "Creator $10/mo; Plus $30/mo", domains: "Paid plans", branding: "Creator Plus and Max", analytics: "Page and commerce reporting", fees: "9% on Free / Creator; 0% on Plus / Max, plus processor fees" },
    sources: [{ label: "Beacons plans", href: "https://help.beacons.ai/en/articles/4695681" }, { label: "Selling fees", href: "https://help.beacons.ai/en/articles/4700289" }],
  },
  "lnk-bio": {
    topic: "One-time plans & ongoing campaigns",
    description: "Lnk.Bio offers a broad page builder with monthly and one-time plan options. Compare its publishing tools with Linktery’s routing workflow, and include recurring add-ons in the cost.",
    question: "Is a one-time page plan enough for your campaign workflow?",
    strengths: ["Monthly and lifetime purchase options", "Page layouts, embeds, and scheduled links", "Newsletter integrations and analytics"],
    checks: ["Separate the one-time plan price from recurring domain, booking, or shop add-ons.", "Recreate one page with the actual embeds, layout, and scheduled content you use—not just its first few links.", "Check the required analytics dimensions and routing rules independently; a layout comparison cannot establish campaign parity."],
    facts: { free: "$0 with unlimited links", paid: "Mini $0.99/mo or $9.99 one-time", domains: "$29.99/year add-on on paid plans", branding: "Unique $24.99 one-time", analytics: "Basic free; advanced on paid plans", fees: "Check Shop and payment-provider terms" },
    sources: [{ label: "Lnk.Bio features and plans", href: "https://lnk.bio/all-features" }],
  },
  bento: {
    topic: "Rebuilding a visual portfolio",
    description: "Moving a Bento page is a portfolio-rebuilding task, not just a pricing comparison. Keep the hierarchy of your work, media, and contact links while choosing a new public address.",
    question: "Which parts of your portfolio must survive the move?",
    strengths: ["Inventory your project tiles and outbound links", "Keep original images, videos, and portfolio copy", "Record the order and visual hierarchy of your work"],
    checks: ["Bento’s official landing page carries a sunset notice. Verify what account access or exports remain available before relying on an import.", "Rebuild from your own source assets. Do not assume another tool can reproduce Bento widgets or its grid exactly.", "Replace the old address across social accounts, signatures, and portfolio references; a new Linktery page cannot take ownership of a bento.me URL."],
    facts: { free: "Legacy service", paid: "See sunset notice", domains: "Plan a new publishing address" },
    notice: "Bento’s official site announces its sunset. This page is a migration checklist, not an offer comparison for a currently available Bento plan.",
    migrationOnly: true,
    sources: [{ label: "Bento sunset notice", href: "https://landing.bento.me/" }],
  },
  "link-me": {
    topic: "Creator operations & multiple profiles",
    description: "Linkme combines profiles with monetization, audience tools, and mobile management. Compare the parts you actually use with Linktery’s profile-and-link workspace.",
    question: "Which creator tools would need a separate replacement?",
    strengths: ["Digital products, merchandise, and paid content", "Mobile account management", "Global analytics and multiple-client workflows"],
    checks: ["Inventory merchandise, courses, paywalled content, and email tools before replacing a Linkme profile.", "Trial the number of profiles you need in each account. Multiple profiles and collaborative team seats are different requirements.", "Check how visitors move from each public profile to an offer, and which analytics remain available after the change."],
    facts: { free: "Free entry advertised", analytics: "Global clicks, engagement, and earnings" },
    sources: [{ label: "Linkme product overview", href: "https://link.me/" }],
  },
  taplink: {
    topic: "Micro-sites & app destinations",
    description: "Taplink builds compact sites with media, messaging, forms, and sales blocks. Compare its page-building depth with the routing controls needed behind your campaign links.",
    question: "Do you need a micro-site, a routing layer, or both?",
    strengths: ["Flexible page blocks and messaging buttons", "Forms, payments, and digital products on Business", "Social links designed to open supported apps"],
    checks: ["Match your forms, payment blocks, and product delivery requirements; Linktery is not a replacement for Taplink’s checkout tools.", "Try your real social-app destinations on iOS and Android. Both app support and browser behavior affect the handoff.", "Compare Business domain and branding controls with the Linktery plan you need, including the number of public profiles."],
    facts: { free: "Basic plan", paid: "Pro and Business", domains: "Business plan", branding: "Business plan", apps: "Smart social links open supported apps", analytics: "Views; click analytics on Pro / Business", fees: "Check payment integration terms" },
    sources: [{ label: "Taplink features and plans", href: "https://taplink.at/en/" }],
  },
  shorby: {
    topic: "Social pages & messenger traffic",
    description: "Compare a Shorby Smart Page with the Linktery workflow you would use for campaign links and messaging destinations. Start with your published page, then test its most important click paths.",
    question: "Can visitors reach the right conversation or campaign?",
    strengths: ["Smart Pages for social-bio traffic", "Messenger destinations alongside website links", "A focused collection of social and content links"],
    checks: ["Copy every messenger URL and test its number, account, and prefilled text on a real phone.", "Confirm current Shorby plan limits directly; this review does not reuse older advertised subscription prices.", "If you rely on a domain or tracking integration, verify ownership and migration steps before replacing your live bio link."],
    facts: { free: "Trial advertised; confirm terms" },
    sources: [{ label: "Shorby Smart Pages", href: "https://shor.by/" }],
  },
  campsite: {
    topic: "Rich profiles & brand ownership",
    description: "Campsite.bio supports rich bio pages with carousels, feeds, and brand controls. The decision is whether those presentation and collaboration tools, or traffic-routing rules, are central to your work.",
    question: "Which page components and account controls are essential?",
    strengths: ["Carousels, feeds, link groups, and opt-in forms", "Custom domains and branding controls on Pro", "Collaborators and organization workflows"],
    checks: ["Rebuild a carousel, feed, and opt-in flow with real content to identify any component you would need to replace.", "Check collaboration separately. Linktery’s Agency plan manages multiple profiles but does not currently include seats or roles.", "Compare reporting retention and exports alongside country or device routing; these solve different operational problems."],
    facts: { free: "Free plan", paid: "Pro and Pro+", domains: "Pro feature", branding: "Pro feature", analytics: "Advanced analytics; plan-dependent depth" },
    sources: [{ label: "Campsite product and Pro features", href: "https://campsite.bio/" }],
  },
  milkshake: {
    topic: "Phone-first publishing & web editing",
    description: "Milkshake is built around creating and updating a website from your phone. Compare that mobile publishing experience with managing profiles and traffic from Linktery’s web dashboard.",
    question: "Where do you prefer to edit, publish, and measure?",
    strengths: ["iOS and Android website editing", "Swipeable, visual website cards", "Paid domain, analytics, and marketing options"],
    checks: ["Recreate the order of your Milkshake cards and check how the same content reads as a Linktery profile.", "Try editing on the devices you use every day. A desktop workflow is useful only if it fits your routine.", "Check the current Pro+ offering: Milkshake lists custom domains and Google Analytics, so do not base a switch on older feature comparisons."],
    facts: { free: "Free app and website entry", paid: "Paid plans; region and billing term vary", domains: "Pro+ plan", analytics: "Insights; Google Analytics on Pro+", fees: "Selling fees depend on plan" },
    sources: [{ label: "Milkshake product and pricing", href: "https://milkshake.app/" }],
  },
  "bio-link": {
    topic: "Audience tools & destination control",
    description: "Bio.link combines customizable pages with posts, email collection, and an AI assistant. Compare that audience-facing toolkit with Linktery’s managed destinations and campaign reporting.",
    question: "Do visitors need content and answers, or a directed next step?",
    strengths: ["Custom themes, apps, and embedded content", "Posts, email collection, and an AI assistant", "Custom domains and real-time statistics"],
    checks: ["Identify posts, subscriber lists, and assistant content you need to retain outside the replacement profile.", "Compare billing periods carefully; a monthly equivalent on an annual plan is not a month-to-month price.", "Build one real destination rule and check its fallback. Page customization alone does not establish routing support."],
    facts: { paid: "Pro; check billing period", domains: "Listed in Pro offering", analytics: "Real-time statistics" },
    sources: [{ label: "Bio.link product and Pro plan", href: "https://bio.link/" }],
  },
  "direct-me": {
    topic: "Audience ownership & external offers",
    description: "Direct.me brings content, email collection, and creator profiles together. Compare the audience tools you use there with a Linktery page that sends visitors to your existing destinations.",
    question: "How will you preserve the audience relationship?",
    strengths: ["Custom profile themes", "Direct email and audience collection", "Live analytics and VIP brand controls"],
    checks: ["Plan where subscriber information and ongoing communication will live before replacing your page.", "Check current VIP terms for domains, integrations, and branding instead of relying on older Pro prices.", "Follow a visitor from the bio link to your offer and confirm that any campaign parameters arrive intact."],
    facts: { free: "Free entry", paid: "VIP; confirm current terms", domains: "VIP feature", analytics: "Live analytics" },
    sources: [{ label: "Direct.me product overview", href: "https://direct.me/" }],
  },
  flowpage: {
    topic: "QR journeys & branded destinations",
    description: "Flowcode’s current mobile-destination offering is presented as FlowHubs. For an existing Flowpage setup, compare the complete scan-to-destination journey rather than treating it as only a bio page.",
    question: "Who controls the printed QR code and the destination behind it?",
    strengths: ["Branded mobile hubs in the Flowcode ecosystem", "Personalized content and offers", "Enterprise data and governance workflows"],
    checks: ["Inventory printed QR codes before changing anything. A code tied to another provider’s domain may still depend on that account.", "Ask Flowcode which current offering and plan correspond to your existing Flowpage account.", "Verify CRM and data integrations independently; Linktery does not claim parity with Flowcode enterprise governance."],
    facts: { paid: "Confirm current Flowcode offering", routing: "Personalized hubs; confirm exact rule support", analytics: "Flowcode platform reporting" },
    notice: "Flowcode’s former /page address now leads to its FlowHubs product. Check your account’s current product and contract terms.",
    sources: [{ label: "Flowcode FlowHubs", href: "https://www.flowcode.com/product/flowhubs" }],
  },
  koji: {
    topic: "Replacing a retired creator page",
    description: "Koji is a migration case rather than an active subscription comparison. Rebuild the public entry point and choose separate homes for any products or interactive experiences you previously published.",
    question: "What needs rebuilding beyond the public links?",
    strengths: ["Recover the list of your published destinations", "Keep copies of products and original content", "Separate the replacement page from commerce tools"],
    checks: ["Linktree announced that Koji would sunset on January 31, 2024. Do not plan around a new Koji subscription.", "Use copies you already control to rebuild the page; Linktery does not offer a guaranteed Koji import or recovery service.", "Update old bios, video descriptions, and campaign materials, then test every replacement URL."],
    facts: { free: "Retired service", paid: "Not an active plan comparison", domains: "Choose a new address" },
    notice: "Koji was sunset following its acquisition by Linktree. This guide focuses on rebuilding, not comparing historical prices as current offers.",
    migrationOnly: true,
    sources: [{ label: "Linktree’s Koji announcement", href: "https://linktr.ee/blog/linktree-acquires-link-in-bio-platform-koji" }],
  },
  carrd: {
    topic: "One-page websites & managed links",
    description: "Carrd is a one-page website builder with forms, embeds, and custom domains. Linktery is more narrowly focused on public profiles and managing where campaign links send visitors.",
    question: "Are you replacing a website or adding a link-management layer?",
    strengths: ["Flexible one-page site construction", "Forms and third-party widgets", "Annual Pro plans with domain and analytics options"],
    checks: ["List custom forms, scripts, and embeds on your Carrd site. A public-profile builder may not reproduce them.", "Keep annual and monthly prices separate: Carrd’s Pro Standard is billed yearly, while Linktery’s displayed plans are monthly.", "Consider keeping Carrd as the destination and using a managed Linktery link in front of it when the site itself already works well."],
    facts: { free: "Free account", paid: "Pro Lite $9/year; Standard $19/year", domains: "Pro Standard and above", branding: "Pro Lite and above", analytics: "Third-party integrations from Pro Standard", fees: "Check connected checkout-provider terms" },
    sources: [{ label: "Carrd Pro plans", href: "https://carrd.co/pro" }],
  },
  fanlink: {
    topic: "Music releases & campaign routing",
    description: "FanLinks are ToneDen’s music smart links, connecting a release to streaming and download services. Compare music-specific release tools separately from general-purpose profile and traffic management.",
    question: "Do you need a release campaign or a flexible public profile?",
    strengths: ["Music-service destination pages", "Pre-save workflows for upcoming releases", "Custom-domain setup for Smart Links"],
    checks: ["Keep any pre-save campaign in a tool that supports it; Linktery does not claim native Spotify or Apple Music pre-save automation.", "Test each streaming destination on mobile with and without the corresponding app installed.", "Separate artist-profile links from release-specific landing pages. You may need both instead of a one-for-one replacement."],
    facts: { domains: "Documented by ToneDen; confirm plan", apps: "Music-service links; test each handoff", analytics: "Confirm current reporting and retention" },
    sources: [{ label: "ToneDen link types", href: "https://developers.toneden.io/docs/fanlinks" }, { label: "FanLink pre-saves", href: "https://toneden.gitbook.io/toneden-help-center/smart-links-and-custom-domains/fanlinks-for-upcoming-music-releases-pre-save-links" }, { label: "Custom domains", href: "https://toneden.gitbook.io/toneden-help-center/smart-links-and-custom-domains/custom-domains-and-smart-links-faqs-and-troubleshooting" }],
  },
  ohmybio: {
    topic: "Routing rules & reporting details",
    description: "OhMyBio lists bio pages, short URLs, QR codes, targeting, and analytics. This is a comparison of workflow details—not a claim that only Linktery can route or measure traffic.",
    question: "Which implementation fits the rules your campaigns need?",
    strengths: ["Country, device, and language targeting", "A/B tests and tracking pixels", "Custom domains, QR codes, and visitor reporting"],
    checks: ["Test matching and unmatched visitors against the same country and device rules in both products.", "Compare report dimensions, attribution expectations, and plan limits with a small live campaign.", "Recheck current pricing and support terms directly. The public feature page alone does not establish the cost of your setup."],
    facts: { domains: "Supported; confirm plan", routing: "Country, device, and language targeting", analytics: "Visitor, referrer, country, OS, and language data" },
    sources: [{ label: "OhMyBio published features", href: "https://ohmy.bio/" }],
  },
  urmybio: {
    topic: "Planning a multi-profile migration",
    description: "Looking for a UrMy.bio alternative? Start with the profiles, domains, and destinations you need to move, then evaluate Linktery against that inventory.",
    question: "How many profiles and owned domains must move together?",
    strengths: ["Document the pages and domains in your current account", "Record active destinations and campaign parameters", "Keep original content and analytics exports you control"],
    checks: ["Confirm UrMy.bio’s current availability, plan terms, and export options with the provider. We could not verify a current public plan sheet.", "Trial the required profile count in Linktery, including independent designs and destinations for each brand.", "Plan DNS changes only for domains you own. Do not assume provider-hosted handles can move between services."],
    notice: "Current UrMy.bio pricing and feature entitlements were not independently verified. Unconfirmed fields are intentionally not presented as facts.",
    migrationOnly: true,
    sources: [],
  },
  bitly: {
    topic: "Short links & routing workflows",
    description: "Bitly spans short URLs, branded links, QR codes, landing pages, and analytics. Compare that broad link-management platform with Linktery’s profile, destination, and traffic-rule workflow.",
    question: "Which link limits, reporting windows, and routing rules matter?",
    strengths: ["Branded short links and QR codes", "Landing pages and click / scan reporting", "Mobile deep linking on higher plans"],
    checks: ["Compare monthly creation limits with the number of links you need to keep and manage; these are not interchangeable quotas.", "Choose the reporting window you actually need. Bitly’s data retention and analytics detail vary across plans.", "Keep custom-domain ownership, API requirements, and mobile deep-link behavior on the migration checklist, not only the subscription price."],
    facts: { free: "$0 · 5 links/month", paid: "Core $10/mo, billed $120/year", domains: "Growth and above", branding: "Check landing-page plan", routing: "Confirm required country-rule workflow", apps: "Premium and Enterprise", analytics: "Click / scan data; retention varies by plan", fees: "Check connected commerce-provider terms" },
    sources: [{ label: "Bitly official pricing", href: "https://bitly.com/pages/pricing" }],
  },
};
