interface EditorialSection { title: string; body: string; steps: string[] }
interface Editorial {
  verdict: string;
  sections: EditorialSection[];
  faq: { question: string; answer: string }[];
  sources: { label: string; href: string }[];
  related: { label: string; href: string }[];
}

// Pair-specific editorial analysis, not paid-product testing or measured
// performance claims. Source checks: 2026-09-05. Scenarios are illustrative.
export const comparisonEditorial: Record<string, Editorial> = {
  "bitly-vs-linktree": {
    verdict: "For a campaign that already has a destination, start by evaluating Bitly’s managed links. For visitors who need to choose between your shop, content, and newsletter, evaluate Linktree’s bio page. The decisive question is whether the visitor needs a redirect or a menu—not which product has more features.",
    sections: [
      { title: "A paid placement with one destination", body: "Imagine three Telegram placements promoting the same webinar. Give each placement a separate tagged URL so that source performance remains distinguishable. Sending everyone to a multi-link page adds a choice that this campaign may not need. Neither a short-link click nor a bio-page visit proves that someone registered for the webinar.", steps: ["Keep campaign and placement names consistent in UTM parameters.", "Test the destination URL after the complete redirect chain.", "Reconcile click data with registrations recorded by the webinar platform."] },
      { title: "An evergreen profile with several destinations", body: "A podcast host may need episodes, sponsorship details, and a newsletter behind one social-bio address. Here the page itself is useful: visitors arrive with different goals. Bitly also offers landing pages, so do not compare its short-link editor with Linktree’s full page and conclude that Bitly cannot publish a hub.", steps: ["Build the same three destinations in both page editors.", "Check how easily the current episode can be promoted without hiding contact information.", "Inspect outbound clicks separately from total page visits."] },
      { title: "Buying capacity, not just a monthly price", body: "Bitly’s published entry plans distinguish link creation quotas, QR codes, and reporting. Its Core price of $10 per month is an annual $120 charge, not a monthly contract. Linktree lists different analytics and commerce entitlements by tier. Compare the resources you need to create during a busy month before comparing the headline price.", steps: ["Count new campaign URLs and QR codes, not only existing links.", "Verify history retention and export access for the reporting period you need.", "Check domain entitlement before printing or distributing branded addresses."] },
      { title: "What survives a switch?", body: "A provider-owned address is not an asset you can move by changing DNS. Keep the old destinations working while replacing published URLs. With a domain you own, check the replacement service’s exact hostname and path model: domain support alone does not guarantee that every existing short path can be recreated.", steps: ["Inventory bios, posts, emails, and printed QR codes separately.", "Export the available reports before closing the old account.", "Keep a rollback list of old addresses and final destinations."] },
    ],
    faq: [
      { question: "Do I need a short link or a link-in-bio page?", answer: "Use a short link when the campaign has one intended destination. Use a page when visitors should choose between destinations. A creator can need both: a permanent bio page and separate measurable campaign URLs." },
      { question: "Can Bitly also create a landing page?", answer: "Yes. Bitly’s current offering includes landing pages as well as short links and QR codes. Compare the actual page layouts and plan limits rather than treating the products as mutually exclusive categories." },
      { question: "Will either click report tell me how many sales I made?", answer: "A click is not a completed purchase. Use consistent campaign tags and the destination’s order or registration data to connect traffic to outcomes; do not divide unrelated page views and sales totals and call it attribution." },
      { question: "Can I keep my existing short URLs when moving?", answer: "Only if you control the address and the replacement supports its domain and path structure. You cannot transfer ownership of a bit.ly or linktr.ee URL to another provider. Keep old links available during the transition." },
    ],
    sources: [{ label: "Bitly: current product and plan scope", href: "https://bitly.com/pages/pricing" }, { label: "Linktree: current plan scope", href: "https://linktr.ee/s/pricing" }],
    related: [{ label: "Short URLs versus bio pages", href: "/guides/url-shortener-vs-link-in-bio" }, { label: "Track link clicks with campaign context", href: "/guides/how-to-track-link-clicks" }],
  },
  "beacons-vs-linktree": {
    verdict: "Evaluate Beacons first when the page is part of a creator business with products, email, and media-kit workflows. Evaluate Linktree when organizing the public entry point is the immediate job. Both include selling features; the choice depends on the checkout and audience operations you actually intend to run.",
    sections: [
      { title: "Selling a downloadable workshop", body: "Map the whole purchase, not just the product tile: checkout, delivery, receipt, refund handling, and follow-up email. A polished bio page can still leave important work in another service. Rebuild one real product journey before committing to move your catalogue.", steps: ["Use a test product and the provider’s permitted test-payment workflow.", "Check where customer records and product files live.", "Confirm what remains accessible after cancelling the plan."] },
      { title: "Subscription cost versus selling fees", body: "Beacons publishes percentage fees that differ by plan, while Linktree’s current plans also distinguish selling fees. Model your own eligible sales volume. Illustratively, a nine-percentage-point fee difference on $1,000 of eligible sales is $90 before subscriptions, processor charges, tax, and refunds. This is arithmetic, not a revenue forecast or a full cost comparison.", steps: ["Use the same currency, billing period, and product category.", "Separate platform selling fees from payment-processor charges.", "Recalculate with your actual refunds and monthly volume, not gross followers."] },
      { title: "Working with a sponsor", body: "Beacons includes a creator media-kit workflow. If brand partnerships are a regular part of your work, test how a sponsor reaches audience information and contacts you. If sponsorship details already live on your website, a public bio link to that page may be sufficient; replacing tools you already use can add unnecessary migration work.", steps: ["Prepare one sponsor inquiry and follow its path end to end.", "Check which audience figures are connected versus manually entered.", "Confirm who owns the final contact list and how it can be exported."] },
      { title: "Keep the audience relationship portable", body: "Changing the public URL does not automatically move subscribers, purchase history, automations, or consent records. Treat these as separate workstreams. When considering Linktery as another option, account for the external commerce stack: Linktery manages profiles and traffic, not digital-product fulfilment.", steps: ["Inventory subscribers, files, automations, and published links.", "Check export formats and migration permissions before importing contacts.", "Test the replacement journey before editing every social bio."] },
    ],
    faq: [
      { question: "Is this just a comparison of two bio-page builders?", answer: "No. The important overlap includes selling and audience workflows. Compare the full process you need, including checkout, delivery, emails, and reporting, rather than only the first screen." },
      { question: "How should I compare selling fees?", answer: "Calculate subscription plus eligible sales multiplied by the applicable platform fee, then add processor charges and other applicable costs. Use current terms for the exact product category; a headline zero-platform-fee offer does not mean payments have no costs." },
      { question: "What if I already sell through an external store?", answer: "Then test the route to that store and campaign attribution first. Bundled commerce features may be less important than page maintenance, tracking, and preserving your existing checkout." },
      { question: "Can Linktery replace the whole creator-commerce stack?", answer: "No. Linktery can provide the profile and managed links, but it does not process purchases or deliver digital products. Keep a suitable checkout and fulfilment service if those are essential." },
    ],
    sources: [{ label: "Beacons: commerce and audience plans", href: "https://beacons.ai/i/pricing" }, { label: "Linktree: selling and analytics tiers", href: "https://linktr.ee/s/pricing" }],
    related: [{ label: "Measure bio-page engagement", href: "/guides/link-in-bio-analytics-guide" }, { label: "Plan a bio-page migration", href: "/guides/migrate-from-linktree-to-linktery" }],
  },
  "carrd-vs-linktree": {
    verdict: "Choose around publishing work: Carrd is worth evaluating for a designed one-page website with forms or embeds; Linktree is worth evaluating for a regularly updated collection of destinations. A consultant’s lead-generation page and a creator’s changing social bio may look similar but require different maintenance.",
    sections: [
      { title: "A consultant collecting qualified leads", body: "A service page may need an explanation, proof, a qualifying form, and a booking destination—not simply a row of links. Carrd’s Pro offering includes forms and embeds. Build the fields and error states you need, then test where a submitted lead actually arrives.", steps: ["Submit a valid inquiry and an intentionally incomplete one.", "Verify notification delivery and the connected contact system.", "Test the embedded booking flow on a narrow mobile screen."] },
      { title: "A creator updating links every week", body: "A feed of new releases calls for quick changes and a clear hierarchy. Measure the editorial work: can someone update the featured item without disturbing the rest of the page? Do not equate visual flexibility with faster maintenance; evaluate the person who will actually operate the page.", steps: ["Prepare five destinations and mark one as the current priority.", "Replace that priority using each editor, without rebuilding the layout.", "Check link labels, focus order, and tap targets on a phone."] },
      { title: "Domain ownership and annual billing", body: "Carrd lists Pro Standard at $19 per year with custom domains; its cheaper Pro Lite does not list that capability. Linktree’s help page says its linktr.ee page address cannot be replaced with a custom domain. Forwarding your own domain to a hosted URL is not the same as hosting the page on that domain.", steps: ["Decide which address should remain visible after loading.", "Include domain registration separately from the website subscription.", "Compare annual totals with annual totals before deciding which is cheaper."] },
      { title: "Forms, page analytics, and redirect analytics", body: "Carrd supports optional analytics integrations. Decide which events matter: a visit, a button click, a successful form, or a confirmed booking. Those are different stages. If the job is country-based campaign routing rather than building a website, separately evaluate a managed-link tool instead of expecting the page editor to solve it.", steps: ["Define one success event before configuring analytics.", "Verify that a form error is not counted as a submitted lead.", "Check privacy settings and cross-domain behaviour of external embeds."] },
    ],
    faq: [
      { question: "Can Carrd be used as a link-in-bio page?", answer: "A one-page website can contain your bio destinations. The question is whether you want to manage a website layout or a dedicated bio-page workflow, and which forms or embeds you need beyond links." },
      { question: "Which option supports a page on my own domain?", answer: "Carrd lists custom-domain publishing in Pro Standard and higher relevant tiers. Linktree says a custom domain cannot replace its linktr.ee page URL. Domain forwarding does not change that hosting distinction." },
      { question: "Does the $19 Carrd price mean $19 each month?", answer: "No. Carrd lists Pro Standard at $19 per year. Domain registration and external services may cost extra. Recheck the current plan sheet before purchasing." },
      { question: "Will either page automatically measure qualified leads?", answer: "Do not assume so. Define and test the successful form or booking event in the relevant reporting system. Page visits and outgoing clicks alone do not establish lead quality." },
    ],
    sources: [{ label: "Carrd: domain, form, and analytics entitlements", href: "https://carrd.com/pro" }, { label: "Linktree: custom-domain limitation", href: "https://linktr.ee/help/en/articles/6571689-can-i-change-the-linktree-url-to-a-custom-domain" }],
    related: [{ label: "Understand custom-domain configuration", href: "/features/custom-domains" }, { label: "Separate URLs from destination pages", href: "/guides/url-shortener-vs-link-in-bio" }],
  },
};
